### PR TITLE
Fix USB-UART bridge exit screen stopping the bridge prematurely

### LINKED ISSUE #3882: GPIO USB UART Bridge disconnects on confirm dialog
### Describe the bug.

Today I found a small bug in GPIO USB UART Bridge. 

When bridge is active, and then you press back, exit confirm dlg appears. This dialog asks left for exit right for stay. But, at this point, is bridge disconnected from USB. I think,  this is a bug. 

Many thanks for fix!

### Reproduction

For best preview, use Putty.

1. Connect to usb
2. Start Putty, select com port, open connection
3. When connection is open, press back on FZ. Exit dlg appears, and Putty will show error, that device is disconnected.

### Target

_No response_

### Logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by portasynthinca3**
# What's new
  - Fixed a bug where the "Exit USB-UART?" confirmation screen would stop the bridge prematurely, without waiting for the user's input. Fix #3882
  - Refactored related code

# Verification 
  - Open the USB-UART bridge
  - Configure bridge to use channel 1
  - Press the back key
  - Verify that the "Exit USB-UART" screen shows up but that the virtual COM port remains attached
  - Verify that selecting "Stay" returns to the main screen
  - Press the back key again
  - Verify that selecting "Exit" returns to the main GPIO screen and disposes of the virtual COM port

# Checklist (For Reviewer)
- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

File: applications/main/gpio/scenes/gpio_scene_usb_uart.c [hunk 1]
```diff
@@ -39,10 +45,18 @@ void gpio_scene_usb_uart_on_enter(void* context) {
 bool gpio_scene_usb_uart_on_event(void* context, SceneManagerEvent event) {
     GpioApp* app = context;
     if(event.type == SceneManagerEventTypeCustom) {
-        scene_manager_set_scene_state(app->scene_manager, GpioSceneUsbUart, 1);
-        scene_manager_next_scene(app->scene_manager, GpioSceneUsbUartCfg);
+        if(event.event == GpioUsbUartEventConfig) {
```
Comment (skotopes) [inline applications/main/gpio/scenes/gpio_scene_usb_uart.c]: Now it looks overcomplicated. Looks like you want to combine exit and uart scene

**Review by skotopes — CHANGES_REQUESTED** [review]

**Review by skotopes — APPROVED** [review]
