### PR TITLE
[#2589] Correctly aborts when correct key is found

### LINKED ISSUE #2589: Picopass app not reading elite keyed cards anymore.
### Describe the bug.

Hi all,

I just upgraded from ver 0.78.1 to ver 0.81.1 and I’ve found that the picopass app no longer reads elite keyed cards, even ones keyed with the keys in dictionary files. The old version of the app used to read elite keyed cards with the default keys..

Any help would be greatly appreciated with this one, cheers!

### Reproduction

1. Open picopass app
2. Read standard keyed card using ‘Read Card’ function - works
3. Read standard keyed card using ‘Elite Dict. Attack’ function - works
4. Read elite keyed card (default AEA6… key) using ‘Read Card’ function - fails
5. Read elite keyed card (default AEA6… key) using ‘Elite Dict. Attack’ function - fails

### Target

PicoPass app

### Logs

_No response_

### Anything else?

I have tried this on software versions 0.80.1, 0.81.1 and the latest dev build 37fb330b, none seem to work

### PR DESCRIPTION
**Pull request by bettse**
# What's new

- Correctly aborts when correct key is found.
- Fixes https://github.com/flipperdevices/flipperzero-firmware/issues/2589

# Verification 

(all with the Elite Dict. Attack option)
- Try to read standard keyed card: success
- Try to read factory keyed card: success
- Try to read card with Standard iClass key, but using KDF (standard key added to user elite dictionary): success 

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

File: applications/external/picopass/picopass_worker.c [hunk 1]
```diff
@@ -570,7 +570,7 @@ void picopass_worker_elite_dict_attack(PicopassWorker* picopass_worker) {
                 picopass_worker->callback(PicopassWorkerEventFail, picopass_worker->context);
                 break;
             }
-            picopass_worker->callback(PicopassWorkerEventSuccess, picopass_worker->context);
+            picopass_worker->callback(PicopassWorkerEventAborted, picopass_worker->context);
```
Comment (bettse) [inline applications/external/picopass/picopass_worker.c:573]: The terminology is a little weird, it is using "aborted" to mean "stop running the attack" and success to mean keep running. I wanted to do a quick fix, but I think better terms could be found for "continue" and "stop"

**Review by skotopes — APPROVED** [review]
